/*
 * FispanComLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.fispan.dev1.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for AuthToken type.
 */
public class AuthToken {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String accessToken;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String tokenType;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Integer expiresIn;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String scope;

    /**
     * Default constructor.
     */
    public AuthToken() {
    }

    /**
     * Initialization constructor.
     * @param  accessToken  String value for accessToken.
     * @param  tokenType  String value for tokenType.
     * @param  expiresIn  Integer value for expiresIn.
     * @param  scope  String value for scope.
     */
    public AuthToken(
            String accessToken,
            String tokenType,
            Integer expiresIn,
            String scope) {
        this.accessToken = accessToken;
        this.tokenType = tokenType;
        this.expiresIn = expiresIn;
        this.scope = scope;
    }

    /**
     * Getter for AccessToken.
     * The access token in GUID format.
     * @return Returns the String
     */
    @JsonGetter("access_token")
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * Setter for AccessToken.
     * The access token in GUID format.
     * @param accessToken Value for String
     */
    @JsonSetter("access_token")
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    /**
     * Getter for TokenType.
     * The type of the token.
     * @return Returns the String
     */
    @JsonGetter("token_type")
    public String getTokenType() {
        return tokenType;
    }

    /**
     * Setter for TokenType.
     * The type of the token.
     * @param tokenType Value for String
     */
    @JsonSetter("token_type")
    public void setTokenType(String tokenType) {
        this.tokenType = tokenType;
    }

    /**
     * Getter for ExpiresIn.
     * The duration in seconds of the token before it expires.
     * @return Returns the Integer
     */
    @JsonGetter("expires_in")
    public Integer getExpiresIn() {
        return expiresIn;
    }

    /**
     * Setter for ExpiresIn.
     * The duration in seconds of the token before it expires.
     * @param expiresIn Value for Integer
     */
    @JsonSetter("expires_in")
    public void setExpiresIn(Integer expiresIn) {
        this.expiresIn = expiresIn;
    }

    /**
     * Getter for Scope.
     * The scope of the generated token.
     * @return Returns the String
     */
    @JsonGetter("scope")
    public String getScope() {
        return scope;
    }

    /**
     * Setter for Scope.
     * The scope of the generated token.
     * @param scope Value for String
     */
    @JsonSetter("scope")
    public void setScope(String scope) {
        this.scope = scope;
    }

    /**
     * Converts this AuthToken into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AuthToken [" + "accessToken=" + accessToken + ", tokenType=" + tokenType
                + ", expiresIn=" + expiresIn + ", scope=" + scope + "]";
    }

    /**
     * Builds a new {@link AuthToken.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AuthToken.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .accessToken(getAccessToken())
                .tokenType(getTokenType())
                .expiresIn(getExpiresIn())
                .scope(getScope());
        return builder;
    }

    /**
     * Class to build instances of {@link AuthToken}.
     */
    public static class Builder {
        private String accessToken;
        private String tokenType;
        private Integer expiresIn;
        private String scope;



        /**
         * Setter for accessToken.
         * @param  accessToken  String value for accessToken.
         * @return Builder
         */
        public Builder accessToken(String accessToken) {
            this.accessToken = accessToken;
            return this;
        }

        /**
         * Setter for tokenType.
         * @param  tokenType  String value for tokenType.
         * @return Builder
         */
        public Builder tokenType(String tokenType) {
            this.tokenType = tokenType;
            return this;
        }

        /**
         * Setter for expiresIn.
         * @param  expiresIn  Integer value for expiresIn.
         * @return Builder
         */
        public Builder expiresIn(Integer expiresIn) {
            this.expiresIn = expiresIn;
            return this;
        }

        /**
         * Setter for scope.
         * @param  scope  String value for scope.
         * @return Builder
         */
        public Builder scope(String scope) {
            this.scope = scope;
            return this;
        }

        /**
         * Builds a new {@link AuthToken} object using the set fields.
         * @return {@link AuthToken}
         */
        public AuthToken build() {
            return new AuthToken(accessToken, tokenType, expiresIn, scope);
        }
    }
}
