/*
 * FispanComLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.fispan.dev1.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for BasePaymentMethod type.
 */
public class BasePaymentMethod {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String type;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Boolean mDefault;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private BankAccount bankAccount;

    /**
     * Default constructor.
     */
    public BasePaymentMethod() {
    }

    /**
     * Initialization constructor.
     * @param  type  String value for type.
     * @param  mDefault  Boolean value for mDefault.
     * @param  bankAccount  BankAccount value for bankAccount.
     */
    public BasePaymentMethod(
            String type,
            Boolean mDefault,
            BankAccount bankAccount) {
        this.type = type;
        this.mDefault = mDefault;
        this.bankAccount = bankAccount;
    }

    /**
     * Getter for Type.
     * The type of the payment.
     * @return Returns the String
     */
    @JsonGetter("type")
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * The type of the payment.
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for Default.
     * Indicates if the given payment method is to be used by default.
     * @return Returns the Boolean
     */
    @JsonGetter("default")
    public Boolean getDefault() {
        return mDefault;
    }

    /**
     * Setter for Default.
     * Indicates if the given payment method is to be used by default.
     * @param mDefault Value for Boolean
     */
    @JsonSetter("default")
    public void setDefault(Boolean mDefault) {
        this.mDefault = mDefault;
    }

    /**
     * Getter for BankAccount.
     * The bank account associated with the payment methods.
     * @return Returns the BankAccount
     */
    @JsonGetter("bankAccount")
    public BankAccount getBankAccount() {
        return bankAccount;
    }

    /**
     * Setter for BankAccount.
     * The bank account associated with the payment methods.
     * @param bankAccount Value for BankAccount
     */
    @JsonSetter("bankAccount")
    public void setBankAccount(BankAccount bankAccount) {
        this.bankAccount = bankAccount;
    }

    /**
     * Converts this BasePaymentMethod into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BasePaymentMethod [" + "type=" + type + ", mDefault=" + mDefault + ", bankAccount="
                + bankAccount + "]";
    }

    /**
     * Builds a new {@link BasePaymentMethod.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BasePaymentMethod.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .type(getType())
                .mDefault(getDefault())
                .bankAccount(getBankAccount());
        return builder;
    }

    /**
     * Class to build instances of {@link BasePaymentMethod}.
     */
    public static class Builder {
        private String type;
        private Boolean mDefault;
        private BankAccount bankAccount;



        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for mDefault.
         * @param  mDefault  Boolean value for mDefault.
         * @return Builder
         */
        public Builder mDefault(Boolean mDefault) {
            this.mDefault = mDefault;
            return this;
        }

        /**
         * Setter for bankAccount.
         * @param  bankAccount  BankAccount value for bankAccount.
         * @return Builder
         */
        public Builder bankAccount(BankAccount bankAccount) {
            this.bankAccount = bankAccount;
            return this;
        }

        /**
         * Builds a new {@link BasePaymentMethod} object using the set fields.
         * @return {@link BasePaymentMethod}
         */
        public BasePaymentMethod build() {
            return new BasePaymentMethod(type, mDefault, bankAccount);
        }
    }
}
