/*
 * FispanComLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.fispan.dev1.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ErpId type.
 */
public class ErpId {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String id;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private ErpProviderEnum erpProvider;

    /**
     * Default constructor.
     */
    public ErpId() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  erpProvider  ErpProviderEnum value for erpProvider.
     */
    public ErpId(
            String id,
            ErpProviderEnum erpProvider) {
        this.id = id;
        this.erpProvider = erpProvider;
    }

    /**
     * Getter for Id.
     * The internal idenification for the ERP.
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * The internal idenification for the ERP.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for ErpProvider.
     * The erp's provider.
     * @return Returns the ErpProviderEnum
     */
    @JsonGetter("erpProvider")
    public ErpProviderEnum getErpProvider() {
        return erpProvider;
    }

    /**
     * Setter for ErpProvider.
     * The erp's provider.
     * @param erpProvider Value for ErpProviderEnum
     */
    @JsonSetter("erpProvider")
    public void setErpProvider(ErpProviderEnum erpProvider) {
        this.erpProvider = erpProvider;
    }

    /**
     * Converts this ErpId into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ErpId [" + "id=" + id + ", erpProvider=" + erpProvider + "]";
    }

    /**
     * Builds a new {@link ErpId.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ErpId.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .id(getId())
                .erpProvider(getErpProvider());
        return builder;
    }

    /**
     * Class to build instances of {@link ErpId}.
     */
    public static class Builder {
        private String id;
        private ErpProviderEnum erpProvider;



        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for erpProvider.
         * @param  erpProvider  ErpProviderEnum value for erpProvider.
         * @return Builder
         */
        public Builder erpProvider(ErpProviderEnum erpProvider) {
            this.erpProvider = erpProvider;
            return this;
        }

        /**
         * Builds a new {@link ErpId} object using the set fields.
         * @return {@link ErpId}
         */
        public ErpId build() {
            return new ErpId(id, erpProvider);
        }
    }
}
